@startuml
left to right direction
skinparam packageStyle rectangle

actor Guest as G
actor User as U

rectangle "Guest Use Cases" {
    usecase "Registration" as Registration
    usecase "Enter Personal Data" as EnterPersonalData
    usecase "Enter Name" as EnterName
    usecase "Enter Password" as EnterPassword
    usecase "Enter Email Address" as EnterEmailAddress
    usecase "Enter Age" as EnterAge
    usecase "Authenticate" as Authenticate
    usecase "View Utility Bills" as ViewBill_Guest
    usecase "View App Information" as ViewInfo_Guest
    usecase "Add Bill" as AddBill_Guest
    usecase "Delete Bill" as DeleteBill_Guest
    usecase "Update Bill Data" as UpdateBillData_Guest
    usecase "Get Bill Details" as GetBillDetails_Guest
    usecase "Side Menu" as SideMenuG
    usecase "Login" as Login
    usecase "Analyse and tips" as AnalyseTipsGuest
    usecase "Main Menu" as MainMenuG
    usecase "Search" as SearchG


    Registration -.> EnterPersonalData : "extend"
    SideMenuG -.> Login : "include"
    SideMenuG -.> ViewInfo_Guest : "include"
    MainMenuG  -.> ViewBill_Guest : "include"
     MainMenuG  -.> SearchG : "include"
    EnterPersonalData -.> EnterName : "include"
    EnterPersonalData -.> EnterPassword : "include"
    EnterPersonalData -.> EnterEmailAddress : "include"
    EnterPersonalData -.> EnterAge : "include"
     GetBillDetails_Guest -.> AddBill_Guest  : "include"
     GetBillDetails_Guest -.> DeleteBill_Guest : "include"
     GetBillDetails_Guest -.> UpdateBillData_Guest  : "include"
     GetBillDetails_Guest -.> AddBill_Guest  : "include"
      GetBillDetails_Guest -.> AnalyseTipsGuest  : "include"

    G --> Registration
    G --> Authenticate
    G --> GetBillDetails_Guest
    G --> SideMenuG
    G --> MainMenuG
}

rectangle "User Use Cases" {
    usecase "Main Menu" as MainMenu
    usecase "Side Menu" as SideMenu
    usecase "View Personal Account" as ViewAccount
    usecase "Logout" as Logout
    usecase "View Utility Bills" as ViewBill_User
    usecase "View App Information" as ViewInfo_User
    usecase "Add Bill" as AddBill_User
    usecase "Delete Bill" as DeleteBill_User
    usecase "Update Bill Data" as UpdateBillData_User
    usecase "Get Bill Details" as GetBillDetails_User
    usecase "Rate app" as Rating
    usecase "Analyse and tips" as AnalyseTipsuser
    usecase "Search" as SearchU

    SideMenu -.> Logout : "include"
    SideMenu -.> ViewAccount : "include"
    SideMenu -.> ViewInfo_User : "include"
    MainMenu -.> SearchU: "include"
    MainMenu -.> ViewBill_User : "include"
    ViewInfo_User -.> Rating  : "include"
    GetBillDetails_User -.> AddBill_User  : "include"
    GetBillDetails_User -.> DeleteBill_User : "include"
    GetBillDetails_User -.> UpdateBillData_User  : "include"
    GetBillDetails_User -.> AddBill_User  : "include"
    GetBillDetails_User -.>  AnalyseTipsuser  : "include"

    U --> MainMenu
    U --> SideMenu
    U --> GetBillDetails_User
@enduml

